### ISSUE TITLE
Optionally perform cleaning schedule at startup

### ISSUE THREAD

**Issue by jayvdb** [morlandi/django-tables-cleaner#5]
In non-production environments, `cron` is unlikely to be hooked up, and devs are unlikely to be regularly invoking any `cron` app which is part of the environment (django-cron, etc).

OTOH, dev environments often collect lots of useless/stale/irrelevant data, and for sqlite that makes the startup slower, and can drag the whole system performance down while Django is running.  It is worth having the startup be slower due to a cleaning operation, rather than slow due to loading a huge sqlite file.

This may be better as a separate app - one that runs some management commands at startup ;-)  I didnt find one quickly.  (oh, https://github.com/TwigWorld/django-genesis looks like a similar idea)

Also it would be worth adding integration with major Django cron apps, which usually entails adding a `jobs.py` inside the app folder.  e.g. `django-extensions` has a jobs subsystem.

**Comment by jayvdb** [comment]
A more immediate solution is https://github.com/morlandi/django-tables-cleaner/issues/4 , as the command could be run before startup.

**Comment by morlandi** [comment]
@jayvdb, thank you very much for your interest in this project and your suggestions.

I just published a significant refactoring, inspired by your considerations, where the app logic has been moved from the management command to a couple of functions which can be called directly from Python code (for example, when using a Python scheduler instead of cron).

I'm trying to avoid adding external dependencies to this little app, so this seems to me the most appropriate and general way to include some of the use-cases you described
